DROP DATABASE tealdb0;
CREATE DATABASE tealdb0;

CONNECT TO tealdb0;

DROP TABLESPACE tealdb0_space;
DROP BUFFERPOOL tealdb0_pool;

CREATE BUFFERPOOL tealdb0_pool PAGESIZE 16K;
CREATE TABLESPACE tealdb0_space PAGESIZE 16K BUFFERPOOL tealdb0_pool;

CREATE TABLE x_tealalert2event (
  "assoc_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "alert_recid" BIGINT NOT NULL,
  "assoc_type" CHAR NOT NULL,
  "t_event_recid" BIGINT NOT NULL, 
  "comments" VARCHAR(128),
  "disable" VARCHAR(128),
  PRIMARY KEY  ("assoc_id")
);
CREATE VIEW tealalert2event AS SELECT * FROM x_tealalert2event;

CREATE TABLE x_tealalert2alert (
  "assoc_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "alert_recid" BIGINT NOT NULL,
  "assoc_type" CHAR NOT NULL,
  "t_alert_recid" BIGINT NOT NULL,
  "comments" VARCHAR(128),
  "disable" VARCHAR(128),
  PRIMARY KEY  ("assoc_id")
);
CREATE VIEW tealalert2alert AS SELECT * FROM x_tealalert2alert;

CREATE TABLE x_tealcheckpoint (
  "chkpt_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "status" CHAR(1) DEFAULT NULL, 
  "event_recid" BIGINT DEFAULT NULL,
  "data" VARCHAR(1024) DEFAULT NULL,
  "comments" VARCHAR(128),
  "disable" VARCHAR(128),
  PRIMARY KEY  ("chkpt_id")
);
CREATE VIEW tealcheckpoint AS SELECT * FROM x_tealcheckpoint;

CREATE TABLE x_tealalertlog (
  "rec_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "alert_id" CHAR(8) NOT NULL,
  "creation_time" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "severity" CHAR(1) NOT NULL,
  "urgency" CHAR(1) NOT NULL,
  "event_loc_type" VARCHAR(2) NOT NULL,
  "event_loc" VARCHAR(255) NOT NULL,
  "fru_loc" VARCHAR(512) default NULL,
  "recommendation" VARCHAR(2048) NOT NULL,
  "reason" VARCHAR(512) NOT NULL,
  "src_name" VARCHAR(64) NOT NULL,
  "state" SMALLINT default NULL,
  "raw_data" VARCHAR(2048) default NULL,
  "comment" VARCHAR(128),
  "disable" VARCHAR(128),
  PRIMARY KEY  ("rec_id")
);
CREATE VIEW tealalertlog AS SELECT * FROM x_tealalertlog;
CREATE VIEW tealactivealerts AS SELECT * FROM x_tealalertlog WHERE "state" = 1 AND "rec_id" NOT IN (SELECT "t_alert_recid" FROM x_tealalert2alert WHERE "assoc_type" = 'D');


CREATE TABLE x_tealeventlog (
  "rec_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "event_id" CHAR(8) NOT NULL,
  "time_logged" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "time_occurred" TIMESTAMP NOT NULL,
  "src_comp" VARCHAR(128) NOT NULL,
  "src_loc_type" VARCHAR(2) NOT NULL,
  "src_loc" VARCHAR(255) NOT NULL,
  "rpt_comp" VARCHAR(128) default NULL,
  "rpt_loc_type" VARCHAR(2) default NULL,
  "rpt_loc" VARCHAR(255) default NULL,
  "event_cnt" INTEGER default NULL,
  "elapsed_time" BIGINT DEFAULT NULL,
  "raw_data_fmt" BIGINT NOT NULL,
  "raw_data" VARCHAR(1024) default NULL,
  "comments" VARCHAR(128),
  "disable" VARCHAR(128),
  PRIMARY KEY  ("rec_id")
);
CREATE VIEW tealeventlog AS SELECT * FROM x_tealeventlog;

CREATE TABLE x_CNM_1_2 (
  "rec_id" BIGINT NOT NULL,
  "eed_loc_info" VARCHAR(64) NOT NULL,
  "encl_mtms" VARCHAR(20) NOT NULL,
  "pwr_ctrl_mtms" VARCHAR(20) NOT NULL,
  "neighbor_loc_type" VARCHAR(2),
  "neighbor_loc" VARCHAR(256),
  "recovery_file_path" VARCHAR(32) NOT NULL,
  "isnm_raw_data" VARCHAR(1024) NOT NULL,
  "local_port" VARCHAR(256), 
  "local_torrent" VARCHAR(256),
  "local_planar" VARCHAR(256),
  "local_om1" VARCHAR(256),
  "local_om2" VARCHAR(256),
  "nbr_port" VARCHAR(256),
  "nbr_torrent" VARCHAR(256),
  "nbr_planar" VARCHAR(256),
  "nbr_om1" VARCHAR(256),
  "nbr_om2" VARCHAR(256),
  "global_counter" BIGINT,
  "comments" VARCHAR(128) DEFAULT NULL,
  "disable" VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY  ("rec_id")
);
CREATE TABLE x_GPFS_1_1 (
  "rec_id" BIGINT NOT NULL,
  "severity" VARCHAR(256) NOT NULL,
  "node_ip" VARCHAR(256) DEFAULT NULL,
  "sgmgr_ip" VARCHAR(256) DEFAULT NULL,
  "user_unba" VARCHAR(256) DEFAULT NULL,
  "meta_unba" VARCHAR(256) DEFAULT NULL,
  "user_ill_rep" VARCHAR(256) DEFAULT NULL,
  "meta_ill_rep" VARCHAR(256) DEFAULT NULL,
  "user_exposed" VARCHAR(256) DEFAULT NULL,
  "meta_exposed" VARCHAR(256) DEFAULT NULL,
  "pool_name" VARCHAR(256) DEFAULT NULL,
  "pool_status" VARCHAR(256) DEFAULT NULL,
  "pool_usage" INTEGER DEFAULT NULL,
  PRIMARY KEY  ("rec_id")
);

CREATE TABLE x_GPFS_1_2 (
  "rec_id" BIGINT NOT NULL,
  "severity" VARCHAR(256) NOT NULL,
  "fs_name" VARCHAR(256) NOT NULL,
  "node_name" VARCHAR(256) DEFAULT NULL,
  "node_ip" VARCHAR(256) DEFAULT NULL,
  "status" VARCHAR(256) DEFAULT NULL,
  "availability" VARCHAR(256) DEFAULT NULL,
  "fg_name" VARCHAR(256) DEFAULT NULL,
  "meta" VARCHAR(256) DEFAULT NULL,
  "data" VARCHAR(256) DEFAULT NULL,
  "cmd" VARCHAR(256) DEFAULT NULL,
  "my_role" VARCHAR(256) DEFAULT NULL,
  "ck_reason" VARCHAR(256) DEFAULT NULL,
  "other_node" VARCHAR(256) DEFAULT NULL,
  "data_len" INTEGER DEFAULT NULL,
  "err_cnt_client" INTEGER DEFAULT NULL,
  "err_cnt_serv" INTEGER DEFAULT NULL,
  "err_cnt_nsd" INTEGER DEFAULT NULL,
  "rpt_interval" INTEGER DEFAULT NULL,
  "io_length" INTEGER DEFAULT NULL,
  "io_time" INTEGER DEFAULT NULL,
  "start_sector" BIGINT DEFAULT NULL,
  PRIMARY KEY  ("rec_id")
);

CREATE TABLE x_GPFS_1_3 (
  "rec_id" BIGINT NOT NULL,
  "severity" VARCHAR(256) NOT NULL,
  "node_name" VARCHAR(256) NOT NULL,
  "location" VARCHAR(256) DEFAULT NULL,
  "fru" VARCHAR(256) DEFAULT NULL,
  "wwn" VARCHAR(256) DEFAULT NULL,
  "state" VARCHAR(256) DEFAULT NULL,
  "reason" VARCHAR(256) DEFAULT NULL,
  "dev_name" VARCHAR(256) DEFAULT NULL,
  "priority" INTEGER DEFAULT NULL,
  "rem_redund" INTEGER DEFAULT NULL,
  "err" INTEGER DEFAULT NULL,
  PRIMARY KEY  ("rec_id")
);

CREATE TABLE x_GPFS_1_4 (
  "rec_id" BIGINT NOT NULL,
  "severity" VARCHAR(256) NOT NULL,
  "msg_text" VARCHAR(256) DEFAULT NULL,
  "diagnosis" VARCHAR(256) DEFAULT NULL,
  "wait_time" INTEGER DEFAULT NULL,
  "msg_level" INTEGER DEFAULT NULL,
  PRIMARY KEY  ("rec_id")
);

CREATE TABLE x_clusterinfo (
  "cluster_id" VARCHAR(128) NOT NULL,
  "cluster_name" VARCHAR(128) DEFAULT NULL,
  "cluster_type" VARCHAR(128) DEFAULT NULL,
  "min_rel_level" VARCHAR(128) DEFAULT NULL,
  "uid_domain" VARCHAR(128) DEFAULT NULL,
  "rsh_cmd" VARCHAR(128) DEFAULT NULL,
  "rcp_cmd" VARCHAR(128) DEFAULT NULL,
  "prim_server" VARCHAR(128) DEFAULT NULL,
  "sec_server" VARCHAR(128) DEFAULT NULL, 
  "c_ref_time" VARCHAR(128) DEFAULT NULL,
  "n_ref_time" VARCHAR(128) DEFAULT NULL,
  "f_ref_time" VARCHAR(128) DEFAULT NULL,
  "fp_ref_time" VARCHAR(128) DEFAULT NULL,
  "sdr_fs_num" INTEGER DEFAULT NULL,
  "num_nodes" INTEGER DEFAULT NULL,
  "max_blk_size" INTEGER DEFAULT NULL,
  "num_fs" INTEGER DEFAULT NULL,
  "token_server" INTEGER DEFAULT NULL,
  "fail_det_time" INTEGER DEFAULT NULL,
  "tcp_port" INTEGER DEFAULT NULL,
  "min_timeout" INTEGER DEFAULT NULL,
  "max_timeout" INTEGER DEFAULT NULL,
  "num_free_disk" INTEGER DEFAULT NULL,
  "change" INTEGER NOT NULL,
  "health" INTEGER NOT NULL,
  PRIMARY KEY  ("cluster_id")
);


CREATE TABLE x_clusterinfo_tmp (
  "cluster_id" VARCHAR(128) DEFAULT NULL,
  "cluster_name" VARCHAR(128) DEFAULT NULL,
  "cluster_type" VARCHAR(128) DEFAULT NULL,
  "min_rel_level" VARCHAR(128) DEFAULT NULL,
  "uid_domain" VARCHAR(128) DEFAULT NULL,
  "rsh_cmd" VARCHAR(128) DEFAULT NULL,
  "rcp_cmd" VARCHAR(128) DEFAULT NULL,
  "prim_server" VARCHAR(128) DEFAULT NULL,
  "sec_server" VARCHAR(128) DEFAULT NULL, 
  "c_ref_time" VARCHAR(128) DEFAULT NULL,
  "n_ref_time" VARCHAR(128) DEFAULT NULL,
  "f_ref_time" VARCHAR(128) DEFAULT NULL,
  "fp_ref_time" VARCHAR(128) DEFAULT NULL,
  "sdr_fs_num" INTEGER DEFAULT NULL,
  "num_nodes" INTEGER DEFAULT NULL,
  "max_blk_size" INTEGER DEFAULT NULL,
  "num_fs" INTEGER DEFAULT NULL,
  "token_server" INTEGER DEFAULT NULL,
  "fail_det_time" INTEGER DEFAULT NULL,
  "tcp_port" INTEGER DEFAULT NULL,
  "min_timeout" INTEGER DEFAULT NULL,
  "max_timeout" INTEGER DEFAULT NULL,
  "num_free_disk" INTEGER DEFAULT NULL,
  "change" INTEGER DEFAULT NULL,
  "health" INTEGER DEFAULT NULL
);

CREATE TABLE x_nodeinfo (
  "cluster_id" VARCHAR(128) NOT NULL,
  "ip_addr" VARCHAR(128) NOT NULL,
  "node_name" VARCHAR(128) DEFAULT NULL,
  "type" VARCHAR(128) DEFAULT NULL,
  "endian" VARCHAR(128) DEFAULT NULL,
  "os_name" VARCHAR(128) DEFAULT NULL,
  "version" VARCHAR(128) DEFAULT NULL,
  "platform" VARCHAR(128) DEFAULT NULL,
  "admin" VARCHAR(128) DEFAULT NULL, 
  "status" VARCHAR(128) DEFAULT NULL,
  "umnt_disk_fail" VARCHAR(128) DEFAULT NULL,
  "healthy" VARCHAR(128) DEFAULT NULL,
  "diag" VARCHAR(128) DEFAULT NULL,
  "pg_pool_size" BIGINT DEFAULT NULL,
  "failure_count" INTEGER DEFAULT NULL,
  "thread_wait" INTEGER DEFAULT NULL,
  "pre_threads" INTEGER DEFAULT NULL,
  "max_MBPS" INTEGER DEFAULT NULL,
  "max_file_cache" INTEGER DEFAULT NULL,
  "max_stat_cache" INTEGER DEFAULT NULL,
  "work1_threads" INTEGER DEFAULT NULL,
  "dm_evt_timeout" INTEGER DEFAULT NULL,
  "dm_mnt_timeout" INTEGER DEFAULT NULL,
  "dm_ses_timeout" INTEGER DEFAULT NULL,
  "nsd_win_mnt" INTEGER DEFAULT NULL,
  "nsd_time_mnt" INTEGER DEFAULT NULL,
  "num_disk_access" INTEGER DEFAULT NULL,
  "change" INTEGER NOT NULL,
  "health" INTEGER NOT NULL,
  PRIMARY KEY  ("cluster_id","ip_addr")
);


CREATE TABLE x_nodeinfo_tmp (
  "cluster_id" VARCHAR(128) DEFAULT NULL,
  "ip_addr" VARCHAR(128) DEFAULT NULL,
  "node_name" VARCHAR(128) DEFAULT NULL,
  "type" VARCHAR(128) DEFAULT NULL,
  "endian" VARCHAR(128) DEFAULT NULL,
  "os_name" VARCHAR(128) DEFAULT NULL,
  "version" VARCHAR(128) DEFAULT NULL,
  "platform" VARCHAR(128) DEFAULT NULL,
  "admin" VARCHAR(128) DEFAULT NULL, 
  "status" VARCHAR(128) DEFAULT NULL,
  "umnt_disk_fail" VARCHAR(128) DEFAULT NULL,
  "healthy" VARCHAR(128) DEFAULT NULL,
  "diag" VARCHAR(128) DEFAULT NULL,
  "pg_pool_size" BIGINT DEFAULT NULL,
  "failure_count" INTEGER DEFAULT NULL,
  "thread_wait" INTEGER DEFAULT NULL,
  "pre_threads" INTEGER DEFAULT NULL,
  "max_MBPS" INTEGER DEFAULT NULL,
  "max_file_cache" INTEGER DEFAULT NULL,
  "max_stat_cache" INTEGER DEFAULT NULL,
  "work1_threads" INTEGER DEFAULT NULL,
  "dm_evt_timeout" INTEGER DEFAULT NULL,
  "dm_mnt_timeout" INTEGER DEFAULT NULL,
  "dm_ses_timeout" INTEGER DEFAULT NULL,
  "nsd_win_mnt" INTEGER DEFAULT NULL,
  "nsd_time_mnt" INTEGER DEFAULT NULL,
  "num_disk_access" INTEGER DEFAULT NULL,
  "change" INTEGER DEFAULT NULL,
  "health" INTEGER DEFAULT NULL
);


CREATE TABLE x_fsinfo (
  "cluster_id" VARCHAR(128) NOT NULL,
  "fs_name" VARCHAR(128) NOT NULL,
  "manager" VARCHAR(128) DEFAULT NULL,
  "status" VARCHAR(128) DEFAULT NULL,
  "x_status" VARCHAR(128) DEFAULT NULL,
  "pool_ref_time" VARCHAR(128) DEFAULT NULL,
  "total_space" BIGINT DEFAULT NULL,
  "total_inodes" BIGINT DEFAULT NULL, 
  "free_inodes" BIGINT DEFAULT NULL,
  "free_space" BIGINT DEFAULT NULL,
  "full_blk_space" BIGINT DEFAULT NULL,
  "sub_blk_space" BIGINT DEFAULT NULL,
  "stg_pool_num" INTEGER DEFAULT NULL,
  "num_mgmt" INTEGER DEFAULT NULL,
  "read_duration" INTEGER DEFAULT NULL,
  "num_mnt_nodes" INTEGER DEFAULT NULL,
  "num_policies" INTEGER DEFAULT NULL,
  "write_duration" INTEGER DEFAULT NULL,
  "was_updated" INTEGER DEFAULT NULL,
  "num_mgr_chg" INTEGER DEFAULT NULL,
  "change" INTEGER NOT NULL,
  "health" INTEGER NOT NULL,
  PRIMARY KEY  ("cluster_id","fs_name")
);


CREATE TABLE x_fsinfo_tmp (
  "cluster_id" VARCHAR(128) DEFAULT NULL,
  "fs_name" VARCHAR(128) DEFAULT NULL,
  "manager" VARCHAR(128) DEFAULT NULL,
  "status" VARCHAR(128) DEFAULT NULL,
  "x_status" VARCHAR(128) DEFAULT NULL,
  "pool_ref_time" VARCHAR(128) DEFAULT NULL,
  "total_space" BIGINT DEFAULT NULL,
  "total_inodes" BIGINT DEFAULT NULL, 
  "free_inodes" BIGINT DEFAULT NULL,
  "free_space" BIGINT DEFAULT NULL,
  "full_blk_space" BIGINT DEFAULT NULL,
  "sub_blk_space" BIGINT DEFAULT NULL,
  "stg_pool_num" INTEGER DEFAULT NULL,
  "num_mgmt" INTEGER DEFAULT NULL,
  "read_duration" INTEGER DEFAULT NULL,
  "num_mnt_nodes" INTEGER DEFAULT NULL,
  "num_policies" INTEGER DEFAULT NULL,
  "write_duration" INTEGER DEFAULT NULL,
  "was_updated" INTEGER DEFAULT NULL,
  "num_mgr_chg" INTEGER DEFAULT NULL,
  "change" INTEGER DEFAULT NULL,
  "health" INTEGER DEFAULT NULL
);

CREATE TABLE x_stgpoolinfo (
  "cluster_id" VARCHAR(128) NOT NULL,
  "fs_name" VARCHAR(128) NOT NULL,
  "stg_name" VARCHAR(128) NOT NULL,
  "status" VARCHAR(128) DEFAULT NULL,
  "refresh_time" VARCHAR(128) DEFAULT NULL,
  "perf_ref_time" VARCHAR(128) DEFAULT NULL,
  "total_space" BIGINT DEFAULT NULL,
  "free_space" BIGINT DEFAULT NULL,
  "parent_fs" INTEGER DEFAULT NULL,
  "num_disks" INTEGER DEFAULT NULL,
  "num_disk_items" INTEGER DEFAULT NULL,
  "change" INTEGER NOT NULL,
  "health" INTEGER NOT NULL,
  PRIMARY KEY  ("cluster_id","fs_name","stg_name")
);

CREATE TABLE x_stgpoolinfo_tmp (
  "cluster_id" VARCHAR(128) DEFAULT NULL,
  "fs_name" VARCHAR(128) DEFAULT NULL,
  "stg_name" VARCHAR(128) DEFAULT NULL,
  "status" VARCHAR(128) DEFAULT NULL,
  "refresh_time" VARCHAR(128) DEFAULT NULL,
  "perf_ref_time" VARCHAR(128) DEFAULT NULL,
  "total_space" BIGINT DEFAULT NULL,
  "free_space" BIGINT DEFAULT NULL,
  "parent_fs" INTEGER DEFAULT NULL,
  "num_disks" INTEGER DEFAULT NULL,
  "num_disk_items" INTEGER DEFAULT NULL,
  "change" INTEGER DEFAULT NULL,
  "health" INTEGER DEFAULT NULL
);

CREATE TABLE x_diskinfo (
  "cluster_id" VARCHAR(128) NOT NULL,
  "disk_name" VARCHAR(128) NOT NULL,
  "node_name" VARCHAR(128) DEFAULT NULL,
  "status" VARCHAR(128) DEFAULT NULL,
  "availability" VARCHAR(128) DEFAULT NULL,
  "pool_name" VARCHAR(128) DEFAULT NULL,
  "vol_id" VARCHAR(128) DEFAULT NULL,
  "meta_data" VARCHAR(128) DEFAULT NULL,
  "data" VARCHAR(128) DEFAULT NULL,
  "disk_wait" VARCHAR(128) DEFAULT NULL,
  "total_space" BIGINT DEFAULT NULL,
  "full_blk_space" BIGINT DEFAULT NULL,
  "sub_blk_space" BIGINT DEFAULT NULL,
  "fail_group_id" INTEGER DEFAULT NULL,
  "is_free" INTEGER DEFAULT NULL,
  "change" INTEGER NOT NULL,
  "health" INTEGER NOT NULL,
  PRIMARY KEY  ("cluster_id","disk_name")
);


CREATE TABLE x_diskinfo_tmp (
  "cluster_id" VARCHAR(128) DEFAULT NULL,
  "disk_name" VARCHAR(128) DEFAULT NULL,
  "node_name" VARCHAR(128) DEFAULT NULL,
  "status" VARCHAR(128) DEFAULT NULL,
  "availability" VARCHAR(128) DEFAULT NULL,
  "pool_name" VARCHAR(128) DEFAULT NULL,
  "vol_id" VARCHAR(128) DEFAULT NULL,
  "meta_data" VARCHAR(128) DEFAULT NULL,
  "data" VARCHAR(128) DEFAULT NULL,
  "disk_wait" VARCHAR(128) DEFAULT NULL,
  "total_space" BIGINT DEFAULT NULL,
  "full_blk_space" BIGINT DEFAULT NULL,
  "sub_blk_space" BIGINT DEFAULT NULL,
  "fail_group_id" INTEGER DEFAULT NULL,
  "is_free" INTEGER DEFAULT NULL,
  "change" INTEGER DEFAULT NULL,
  "health" INTEGER DEFAULT NULL
);

CREATE TABLE x_fsetinfo (
  "cluster_id" VARCHAR(128) NOT NULL,
  "fs_name" VARCHAR(128) NOT NULL,
  "id" VARCHAR(128) NOT NULL,
  "fset_name" VARCHAR(128) DEFAULT NULL,
  "root_inode" VARCHAR(128) DEFAULT NULL,
  "parent_id" VARCHAR(128) DEFAULT NULL,
  "comment" VARCHAR(128) DEFAULT NULL, 
  "status" VARCHAR(128) DEFAULT NULL,
  "path" VARCHAR(128) DEFAULT NULL,
  "created" VARCHAR(128) DEFAULT NULL,
  "inodes" BIGINT DEFAULT NULL,
  "data" BIGINT DEFAULT NULL,
  "version" INTEGER DEFAULT NULL,
  "change" INTEGER NOT NULL,
  "health" INTEGER NOT NULL,
  PRIMARY KEY  ("cluster_id","fs_name","id")
);


CREATE TABLE x_fsetinfo_tmp (
  "cluster_id" VARCHAR(128) DEFAULT NULL,
  "fs_name" VARCHAR(128) DEFAULT NULL,
  "id" VARCHAR(128) DEFAULT NULL,
  "fset_name" VARCHAR(128) DEFAULT NULL,
  "root_inode" VARCHAR(128) DEFAULT NULL,
  "parent_id" VARCHAR(128) DEFAULT NULL,
  "comment" VARCHAR(128) DEFAULT NULL, 
  "status" VARCHAR(128) DEFAULT NULL,
  "path" VARCHAR(128) DEFAULT NULL,
  "created" VARCHAR(128) DEFAULT NULL,
  "inodes" BIGINT DEFAULT NULL,
  "data" BIGINT DEFAULT NULL,
  "version" INTEGER DEFAULT NULL,
  "change" INTEGER DEFAULT NULL,
  "health" INTEGER DEFAULT NULL
);

CREATE TABLE x_rginfo (
  "cluster_id" VARCHAR(128) NOT NULL,
  "rg_name" VARCHAR(64) NOT NULL,
  "rg_act_svr" VARCHAR(64) DEFAULT NULL,
  "rg_svrs" VARCHAR(128) DEFAULT NULL,
  "rg_id" VARCHAR(20) DEFAULT NULL,
  "rg_das" INTEGER DEFAULT NULL,
  "rg_vdisks" INTEGER DEFAULT NULL,
  "rg_pdisks" INTEGER DEFAULT NULL, 
  "change" INTEGER NOT NULL,
  "health" INTEGER NOT NULL,
  PRIMARY KEY  ("cluster_id","rg_name")
);


CREATE TABLE x_rginfo_tmp (
  "cluster_id" VARCHAR(128) DEFAULT NULL,
  "rg_name" VARCHAR(64) DEFAULT NULL,
  "rg_act_svr" VARCHAR(64) DEFAULT NULL,
  "rg_svrs" VARCHAR(128) DEFAULT NULL,
  "rg_id" VARCHAR(20) DEFAULT NULL,
  "rg_das" INTEGER DEFAULT NULL,
  "rg_vdisks" INTEGER DEFAULT NULL,
  "rg_pdisks" INTEGER DEFAULT NULL, 
  "change" INTEGER DEFAULT NULL,
  "health" INTEGER DEFAULT NULL
);

CREATE TABLE x_dainfo (
  "cluster_id" VARCHAR(128) NOT NULL,
  "rg_name" VARCHAR(64) NOT NULL,
  "da_name" VARCHAR(64) NOT NULL,
  "da_bg_task" VARCHAR(32) DEFAULT NULL,
  "da_task_priority" VARCHAR(32) DEFAULT NULL,
  "da_need_service" VARCHAR(8) DEFAULT NULL,
  "da_task_percent" INTEGER DEFAULT NULL,
  "da_vdisks" INTEGER DEFAULT NULL,
  "da_pdisks" INTEGER DEFAULT NULL,
  "da_spares" INTEGER DEFAULT NULL,
  "da_replace_thres" INTEGER DEFAULT NULL,
  "da_free_space" BIGINT DEFAULT NULL,
  "da_scrub_dura" INTEGER DEFAULT NULL,
  "change" INTEGER NOT NULL,
  "health" INTEGER NOT NULL,
  PRIMARY KEY  ("cluster_id","rg_name","da_name")
);

CREATE TABLE x_dainfo_tmp (
  "cluster_id" VARCHAR(128) DEFAULT NULL,
  "rg_name" VARCHAR(64) DEFAULT NULL,
  "da_name" VARCHAR(64) DEFAULT NULL,
  "da_bg_task" VARCHAR(32) DEFAULT NULL,
  "da_task_priority" VARCHAR(32) DEFAULT NULL,
  "da_need_service" VARCHAR(8) DEFAULT NULL,
  "da_task_percent" INTEGER DEFAULT NULL,
  "da_vdisks" INTEGER DEFAULT NULL,
  "da_pdisks" INTEGER DEFAULT NULL,
  "da_spares" INTEGER DEFAULT NULL,
  "da_replace_thres" INTEGER DEFAULT NULL,
  "da_free_space" BIGINT DEFAULT NULL,
  "da_scrub_dura" INTEGER DEFAULT NULL,
  "change" INTEGER DEFAULT NULL,
  "health" INTEGER DEFAULT NULL
);

CREATE TABLE x_vdiskinfo (
  "cluster_id" VARCHAR(128) NOT NULL,
  "rg_name" VARCHAR(64) NOT NULL,
  "da_name" VARCHAR(64) NOT NULL,
  "vdisk_name" VARCHAR(64) NOT NULL,
  "vdisk_raid_code" VARCHAR(32) DEFAULT NULL,
  "vdisk_state" VARCHAR(64) DEFAULT NULL,
  "vdisk_remarks" VARCHAR(32) DEFAULT NULL,
  "vdisk_block_size" INTEGER DEFAULT NULL,
  "vdisk_size" BIGINT DEFAULT NULL,
  "change" INTEGER NOT NULL,
  "health" INTEGER NOT NULL,
  PRIMARY KEY  ("cluster_id","rg_name","da_name","vdisk_name")
);

CREATE TABLE x_vdiskinfo_tmp (
  "cluster_id" VARCHAR(128) DEFAULT NULL,
  "rg_name" VARCHAR(64) DEFAULT NULL,
  "da_name" VARCHAR(64) DEFAULT NULL,
  "vdisk_name" VARCHAR(64) DEFAULT NULL,
  "vdisk_raid_code" VARCHAR(32) DEFAULT NULL,
  "vdisk_state" VARCHAR(64) DEFAULT NULL,
  "vdisk_remarks" VARCHAR(32) DEFAULT NULL,
  "vdisk_block_size" INTEGER DEFAULT NULL,
  "vdisk_size" BIGINT DEFAULT NULL,
  "change" INTEGER DEFAULT NULL,
  "health" INTEGER DEFAULT NULL
);

CREATE TABLE x_pdiskinfo (
  "cluster_id" VARCHAR(128) NOT NULL,
  "rg_name" VARCHAR(64) NOT NULL,
  "da_name" VARCHAR(64) NOT NULL,
  "pdisk_name" VARCHAR(64) NOT NULL,
  "pdisk_dev_path" VARCHAR(64) DEFAULT NULL,
  "pdisk_state" VARCHAR(160) DEFAULT NULL,
  "pdisk_fru" VARCHAR(32) DEFAULT NULL,
  "pdisk_location" VARCHAR(32) DEFAULT NULL,
  "pdisk_repl_prior" INTEGER DEFAULT NULL,
  "pdisk_free_space" BIGINT DEFAULT NULL,
  "change" INTEGER NOT NULL,
  "health" INTEGER NOT NULL,
  PRIMARY KEY  ("cluster_id","rg_name","da_name","pdisk_name")
);

CREATE TABLE x_pdiskinfo_tmp (
  "cluster_id" VARCHAR(128) DEFAULT NULL,
  "rg_name" VARCHAR(64) DEFAULT NULL,
  "da_name" VARCHAR(64) DEFAULT NULL,
  "pdisk_name" VARCHAR(64) DEFAULT NULL,
  "pdisk_dev_path" VARCHAR(64) DEFAULT NULL,
  "pdisk_state" VARCHAR(160) DEFAULT NULL,
  "pdisk_fru" VARCHAR(32) DEFAULT NULL,
  "pdisk_location" VARCHAR(32) DEFAULT NULL,
  "pdisk_repl_prior" INTEGER DEFAULT NULL,
  "pdisk_free_space" BIGINT DEFAULT NULL,
  "change" INTEGER DEFAULT NULL,
  "health" INTEGER DEFAULT NULL
);
CREATE TABLE SITE (
	"key" VARCHAR(128) NOT NULL DEFAULT '', 
	"value" VARCHAR(128), 
	"comments" VARCHAR(128), 
	"disable" VARCHAR(8), 
	PRIMARY KEY("key")
);

ALTER TABLE X_TEALALERT2ALERT ADD CONSTRAINT TEAL_FK_AREC FOREIGN KEY ("alert_recid") REFERENCES X_TEALALERTLOG ("rec_id") ON DELETE CASCADE;
ALTER TABLE X_TEALALERT2ALERT ADD CONSTRAINT TEAL_FK_T_AREC FOREIGN KEY ("t_alert_recid") REFERENCES X_TEALALERTLOG ("rec_id") ON DELETE RESTRICT;
ALTER TABLE X_TEALALERT2ALERT ADD CONSTRAINT TEAL_A2A_ASSOC_CHECK CHECK("assoc_type" IN ('C','S','D'));

ALTER TABLE X_TEALALERT2EVENT ADD CONSTRAINT TEAL_FK_EREC FOREIGN KEY ("alert_recid") REFERENCES X_TEALALERTLOG ("rec_id") ON DELETE CASCADE;
ALTER TABLE X_TEALALERT2EVENT ADD CONSTRAINT TEAL_FK_T_EREC FOREIGN KEY ("t_event_recid") REFERENCES X_TEALEVENTLOG ("rec_id") ON DELETE RESTRICT;
ALTER TABLE X_TEALALERT2EVENT ADD CONSTRAINT TEAL_A2E_ASSOC_CHECK CHECK("assoc_type" IN ('C','S'));

ALTER TABLE X_TEALCHECKPOINT ADD CONSTRAINT TEAL_FK_CHKREC FOREIGN KEY ("event_recid") REFERENCES X_TEALEVENTLOG ("rec_id") ON DELETE RESTRICT;

ALTER TABLE X_TEALALERTLOG ADD CONSTRAINT TEAL_ALERT_STATE_CHECK CHECK ("state" IN (1,2));

CREATE TRIGGER TEAL_DUPALERT_DELETE AFTER DELETE ON X_TEALALERT2ALERT REFERENCING OLD AS OLD FOR EACH ROW BEGIN ATOMIC IF (OLD."assoc_type" = 'D') THEN DELETE FROM X_TEALALERTLOG WHERE "rec_id" = OLD."t_alert_recid"; END IF; END;
CREATE TRIGGER TEAL_ALERTLOG_DELETE BEFORE DELETE ON X_TEALALERTLOG REFERENCING OLD AS OLD FOR EACH ROW BEGIN ATOMIC IF (OLD."state" = 1) THEN SIGNAL SQLSTATE '70003' ('Deletion not permitted'); END IF; END;

DISCONNECT tealdb0;
