# begin_generated_IBM_copyright_prolog
#
# This is an automatically generated copyright prolog.
# After initializing,  DO NOT MODIFY OR MOVE
# ================================================================
#
# (C) Copyright IBM Corp.  2012
# Eclipse Public License (EPL)
#
# ================================================================
#
# end_generated_IBM_copyright_prolog
package xCAT_schema::Teal_ipmi;

# This file contains the schema necessary to support the IPMI component in the TEAL framework

%tabspec = (
     x_IPMI_1_1 => {
        cols => [qw(rec_id 
        			guid 
        			sequence 
        			time_occurred 
        			utc_offset 
        			trap_src 
        			event_src 
        			severity 
        			sensor_dev 
        			sensor_num 
        			entity 
        			entity_inst 
        			event_data1 
        			event_data2 
        			event_data3 
        			event_data4
					event_data5 
					event_data6 
					event_data7 
					event_data8 
					lang_code 
					mfg_id 
					sys_id 
					message 
					comments 
					disable)],
        keys => [qw(rec_id)],
        required => [qw(rec_id message)],
        types => {
            rec_id => 'BIGINT',
            guid => 'CHAR(32)',
            sequence => 'SMALLINT',
            time_occurred => 'INTEGER',
            utc_offset => 'SMALLINT',
            trap_src => 'SMALLINT',
            event_src => 'SMALLINT',
            severity => 'SMALLINT',
            sensor_dev => 'SMALLINT',
            sensor_num => 'SMALLINT',
            entity => 'SMALLINT',
            entity_inst => 'SMALLINT',
            event_data1 => 'SMALLINT',
            event_data2 => 'SMALLINT',
            event_data3 => 'SMALLINT',
            event_data4 => 'SMALLINT',
            event_data5 => 'SMALLINT',
            event_data6 => 'SMALLINT',
            event_data7 => 'SMALLINT',
            event_data8 => 'SMALLINT',
            lang_code => 'SMALLINT',
            mfg_id => 'SMALLINT',
            sys_id => 'SMALLINT',
            message => 'VARCHAR(256)'
        },
        engine => 'InnoDB',  
        tablespace =>'XCATTBS16K', 
        table_desc => 'TEAL IPMI Event Extended Data',
        descriptions => {
            rec_id => 'Database record id of common event',
            guid => 'GUID for the platform, per SMBIOS 2.2 / PXE specifications',
            sequence => 'Used to differentiate a re-transmitted (re-tried) trap from a new trap instance',
            time_occurred => 'Platform local time-based. Encoded as number of seconds from 0:00 1/1/98.',
            utc_offset => 'UTC Offset in minutes.',
            trap_src => 'Class of the device or software that originated the trap on the network.',
            event_src => 'Class of device or type of software that originated the event: This can be different than the device or type of software that sends the trap.',
            severity => 'Severity (based on DMI Event Severity).',
            sensor_dev => 'Identifies the instance of the device that holds the sensor that generated the event.',
            sensor_num => 'The Sensor Number field is used to identify a given instance of a sensor relative to the Sensor Device.',
            entity => 'Entity ID from IPMI v1.0 specification.',
            entity_inst => 'Indicates which instance of the Entity the event is for.',
            event_data1 => 'Additional parametric data byte—formatted as specified by Event Type in combination with Event Source.',
            event_data2 => '',
            event_data3 => '',
            event_data4 => '',
            event_data5 => '',
            event_data6 => '',
            event_data7 => '',
            event_data8 => '',
            lang_code => 'Per IPMI v1.0 FRU Information Format.',
            mfg_id => 'Manufacturer ID using Private Enterprise IDs per IANA.',
            sys_id => 'Specified by manufacturer given by Manufacturer ID field, this number can be used to identify the particular system/product model or type.',
            message => 'Detailed event message generated by xCAT',
            comments => 'Any user-written notes.',
            disable => q(Set to 'yes' or '1' to comment out this row.),
        },
    },
); # end of tabspec definition

1;    

 